### ISSUE TITLE
setwd() in R shiny driver script.

### ISSUE THREAD

**Issue by lashmore** [NCBI-Hackathons/Metabolomics-Data-Portal#2]
People have to update the setwd() command at top of driver script in order for it to run on their local installation. A fix/ work around for this would be ideal.

Example: On my computer, my repo is installed here, so I setwd() to:
setwd("~/Documents/GitHub/Metabolomics-Data-Portal/R/")

**Comment by gvenugopalan** [comment]
Use dotenv to load environment

**Comment by pooranis** [comment]
We got rid of this when we made it a package!!!
